import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it } from 'vitest'
import { WellnessApp as App } from './App'

describe('daily loop', () => {
  beforeEach(() => localStorage.clear())
  it('onboards and rewards a completed activity quest once', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    expect(screen.getByRole('heading', { name: '오늘' })).toBeInTheDocument()
    expect(screen.getByText(/목표 1697 kcal/)).toBeInTheDocument()
    expect(screen.getByText(/단백질 140g/)).toBeInTheDocument()
    expect(screen.getByText(/지방 47g/)).toBeInTheDocument()
    expect(screen.getByText(/탄수화물 179g/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /오늘의 운동 완료/ }))
    expect(screen.getByText('1/3')).toBeInTheDocument()
    expect(screen.getByText(/72\/100 XP/)).toBeInTheDocument()
  })

  it('keeps one atomic live status node mounted while navigating every app view', async () => {
    const user = userEvent.setup()
    render(<App />)
    const status = screen.getByRole('status')
    expect(status).toHaveAttribute('aria-atomic', 'true')

    await user.click(screen.getByRole('button', { name:'시작하기' }))
    expect(screen.getAllByRole('status')).toEqual([status])
    await user.click(screen.getAllByRole('button', { name:'계획' })[0])
    expect(screen.getAllByRole('status')).toEqual([status])
    await user.click(screen.getByRole('button', { name:'오늘' }))
    expect(screen.getAllByRole('status')).toEqual([status])
    await user.click(screen.getByRole('button', { name:'캐릭터 꾸미기' }))
    expect(screen.getAllByRole('status')).toEqual([status])
  })

  it('creates and opens a seven-day weekly plan', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    expect(screen.getAllByTestId('day-plan')).toHaveLength(7)
    expect(screen.getByText('식사 21')).toBeInTheDocument()
  })

  it('synchronizes today activity completion with the weekly summary', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 12, 12)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getByRole('button', { name: '운동 완료' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    expect(screen.getByText('완료 2/26')).toBeInTheDocument()
    expect(screen.getAllByText(/완료됨/)).toHaveLength(2)
  })

  it('restores a generated weekly plan after remounting', async () => {
    const user = userEvent.setup()
    const first = render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    first.unmount()
    render(<App />)
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    expect(screen.getAllByTestId('day-plan')).toHaveLength(7)
  })

  it('opens records, saves today weight, and keeps it after remounting', async () => {
    const user = userEvent.setup()
    const now = () => new Date(2026, 7, 11, 7)
    const first = render(<App now={now} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('heading', { name: '기록' })).toBeInTheDocument()
    await user.type(screen.getByRole('spinbutton', { name: '오늘 체중' }), '71.5')
    await user.click(screen.getByRole('button', { name: '체중 저장' }))
    expect(screen.getByRole('status')).toHaveTextContent('오늘 체중을 저장했어요.')
    first.unmount()
    render(<App now={now} />)
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('spinbutton', { name: '오늘 체중' })).toHaveValue(71.5)
  })

  it('keeps today weight while moving from records to today and back', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 11, 7)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    await user.type(screen.getByRole('spinbutton', { name: '오늘 체중' }), '68.4')
    await user.click(screen.getByRole('button', { name: '체중 저장' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('spinbutton', { name: '오늘 체중' })).toHaveValue(68.4)
    expect(screen.getAllByRole('button', { current: 'page' })).toHaveLength(1)
  })

  it('counts a planned activity and its XP once in records', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 12, 12)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getByRole('button', { name: '운동 완료' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByText('2/5', { selector: 'strong' })).toBeInTheDocument()
    expect(screen.getByText('40', { selector: 'strong' })).toBeInTheDocument()
  })

  it('customizes base appearance and restores it after remounting', async () => {
    const user = userEvent.setup()
    const first = render(<App />)
    await user.click(screen.getByRole('button', { name:'시작하기' }))
    const trigger = screen.getByRole('button', { name:'캐릭터 꾸미기' })
    await user.click(trigger)
    await user.click(screen.getByRole('button', { name:'여성 캐릭터' }))
    await user.click(screen.getByRole('button', { name:'짙은 피부' }))
    await user.click(screen.getByRole('button', { name:'오늘로 돌아가기' }))
    expect(screen.getByRole('img', { name:/여성 캐릭터, 짙은 피부, 짧은 머리/ })).toBeInTheDocument()
    expect(screen.getByRole('button', { name:'캐릭터 꾸미기' })).toHaveFocus()
    first.unmount()
    render(<App />)
    expect(screen.getByRole('img', { name:/여성 캐릭터, 짙은 피부, 짧은 머리/ })).toBeInTheDocument()
  })

  it('unlocks, equips, and restores a level reward without auto-equipping it', async () => {
    const user = userEvent.setup()
    const now = () => new Date(2026, 7, 11, 7)
    const first = render(<App now={now} />)
    await user.click(screen.getByRole('button', { name:'시작하기' }))
    await user.click(screen.getByRole('button', { name:/스무디 기록하기/ }))
    await user.click(screen.getByRole('button', { name:/오늘의 운동 완료/ }))
    await user.click(screen.getByRole('button', { name:/5분 스트레칭/ }))
    expect(screen.getByRole('status')).toHaveTextContent('웨이브 머리, 운동화 아이템을 해금했어요.')
    expect(screen.getByTestId('avatar-unlock-toast')).toHaveTextContent('웨이브 머리, 운동화 아이템을 해금했어요.')
    await user.click(screen.getByRole('button', { name:'캐릭터 꾸미기' }))
    expect(screen.getByRole('status')).toHaveTextContent('웨이브 머리, 운동화 아이템을 해금했어요.')

    const trainers = screen.getByRole('button', { name:'운동화' })
    expect(trainers).toBeEnabled()
    expect(trainers).toHaveAttribute('aria-pressed', 'false')
    expect(screen.getByRole('img', { name:/짧은 머리$/ })).toBeInTheDocument()

    await user.click(trainers)
    expect(trainers).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('img', { name:/짧은 머리, 운동화/ })).toBeInTheDocument()
    first.unmount()

    render(<App now={now} />)
    expect(screen.getByRole('img', { name:/짧은 머리, 운동화/ })).toBeInTheDocument()
  })

  it('reopens completed quests on the next local date and rewards the new event once', async () => {
    const user = userEvent.setup()
    let day = 11
    const now = () => new Date(2026, 7, day, 7)
    const first = render(<App now={now} />)
    await user.click(screen.getByRole('button', { name:'시작하기' }))
    await user.click(screen.getByRole('button', { name:/스무디 기록하기/ }))
    await user.click(screen.getByRole('button', { name:/오늘의 운동 완료/ }))
    await user.click(screen.getByRole('button', { name:/5분 스트레칭/ }))
    expect(screen.getByText('3/3')).toBeInTheDocument()
    first.unmount()

    day = 12
    render(<App now={now} />)
    expect(screen.getByText('0/3')).toBeInTheDocument()
    const mealQuest = screen.getByRole('button', { name:/스무디 기록하기/ })
    expect(mealQuest).toBeEnabled()
    await user.click(mealQuest)
    expect(screen.getByText('1/3')).toBeInTheDocument()
    expect(screen.getByText(/27\/100 XP/)).toBeInTheDocument()
  })
})
