import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it } from 'vitest'
import { App } from './App'

describe('daily loop', () => {
  beforeEach(() => localStorage.clear())
  it('onboards and rewards a completed activity quest once', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    expect(screen.getByRole('heading', { name: '오늘' })).toBeInTheDocument()
    expect(screen.getByText(/목표 1697 kcal/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /오늘의 운동 완료/ }))
    expect(screen.getByText('1/3')).toBeInTheDocument()
    expect(screen.getByText(/72\/100 XP/)).toBeInTheDocument()
  })

  it('creates and opens a seven-day weekly plan', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    expect(screen.getAllByTestId('day-plan')).toHaveLength(7)
    expect(screen.getByText('식사 21')).toBeInTheDocument()
  })

  it('synchronizes today activity completion with the weekly summary', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 10, 12)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getByRole('button', { name: '운동 완료' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    expect(screen.getByText('완료 1/24')).toBeInTheDocument()
    expect(screen.getByText(/완료됨/)).toBeInTheDocument()
  })

  it('restores a generated weekly plan after remounting', async () => {
    const user = userEvent.setup()
    const first = render(<App />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    first.unmount()
    render(<App />)
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    expect(screen.getAllByTestId('day-plan')).toHaveLength(7)
  })

  it('opens records, saves today weight, and keeps it after remounting', async () => {
    const user = userEvent.setup()
    const now = () => new Date(2026, 7, 11, 7)
    const first = render(<App now={now} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('heading', { name: '기록' })).toBeInTheDocument()
    await user.type(screen.getByRole('spinbutton', { name: '오늘 체중' }), '71.5')
    await user.click(screen.getByRole('button', { name: '체중 저장' }))
    expect(screen.getByRole('status')).toHaveTextContent('오늘 체중을 저장했어요.')
    first.unmount()
    render(<App now={now} />)
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('spinbutton', { name: '오늘 체중' })).toHaveValue(71.5)
  })

  it('keeps today weight while moving from records to today and back', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 11, 7)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    await user.type(screen.getByRole('spinbutton', { name: '오늘 체중' }), '68.4')
    await user.click(screen.getByRole('button', { name: '체중 저장' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByRole('spinbutton', { name: '오늘 체중' })).toHaveValue(68.4)
    expect(screen.getAllByRole('button', { current: 'page' })).toHaveLength(1)
  })

  it('counts a planned activity and its XP once in records', async () => {
    const user = userEvent.setup()
    render(<App now={() => new Date(2026, 7, 10, 12)} />)
    await user.click(screen.getByRole('button', { name: '시작하기' }))
    await user.click(screen.getAllByRole('button', { name: '계획' })[0])
    await user.click(screen.getByRole('button', { name: '이번 주 계획 만들기' }))
    await user.click(screen.getByRole('button', { name: '오늘' }))
    await user.click(screen.getByRole('button', { name: '운동 완료' }))
    await user.click(screen.getAllByRole('button', { name: '기록' })[0])
    expect(screen.getByText('1/3', { selector: 'strong' })).toBeInTheDocument()
    expect(screen.getByText('40', { selector: 'strong' })).toBeInTheDocument()
  })

  it('customizes the layered character and restores it after remounting', async () => {
    const user = userEvent.setup()
    const first = render(<App />)
    await user.click(screen.getByRole('button', { name:'시작하기' }))
    const trigger = screen.getByRole('button', { name:'캐릭터 꾸미기' })
    await user.click(trigger)
    await user.click(screen.getByRole('button', { name:'여성 캐릭터' }))
    await user.click(screen.getByRole('button', { name:'짙은 피부' }))
    await user.click(screen.getByRole('button', { name:'웨이브 머리' }))
    await user.click(screen.getByRole('button', { name:'산보복' }))
    await user.click(screen.getByRole('button', { name:'오늘로 돌아가기' }))
    expect(screen.getByRole('img', { name:/여성 캐릭터, 짙은 피부, 웨이브 머리, 산보복/ })).toBeInTheDocument()
    expect(screen.getByRole('button', { name:'캐릭터 꾸미기' })).toHaveFocus()
    first.unmount()
    render(<App />)
    expect(screen.getByRole('img', { name:/여성 캐릭터, 짙은 피부, 웨이브 머리, 산보복/ })).toBeInTheDocument()
  })
})
